### ISSUE TITLE
unable to download weights on google colab

### ISSUE THREAD

**Issue by Saurabhbaghel** [Shiva-sankaran/LineEX#1]
getting the following error: 

` Cannot retrieve the public link of the file. You may need to change the permission to 'Anyone with the link', or have had many accesses. You may still be able to access the file from the browser:
	 https://drive.google.com/uc?id=176BjH_6W-HRoU9RvsysSNW27GVIHPlHV `

Thanks

**Comment by Shiva-sankaran** [comment]
The download link might have been used too many times, we will move the weights and data files to file server very soon. Until then, please download the weights and data and move them to the corresponding folders. If you are interested you are welcome to contribute to the project by writing a new shell script which will handle the downloading and moving of files.

**Comment by halqadasi** [comment]
> The download link might have been used too many times, we will move the weights and data files to file server very soon. Until then, please download the weights and data and move them to the corresponding folders. If you are interested you are welcome to contribute to the project by writing a new shell script which will handle the downloading and moving of files.

I did not understand how I can do that **Until then, please download the weights and data and move them to the corresponding folders**. The link is inaccessible even manually. Could you please create a new link? I do think it is because of excessive number of downloads.

**Comment by Shiva-sankaran** [comment]
Hi @halqadasi ,

If you have not already noticed we have [moved](https://github.com/Shiva-sankaran/LineEX#update-dataset-moved-to-here) our data to [here](https://iitgnacin-my.sharepoint.com/personal/md_hassan_iitgn_ac_in/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fmd%5Fhassan%5Fiitgn%5Fac%5Fin%2FDocuments%2FLineEx&ga=1)

**Comment by Kalaiyarasi-Cellappan** [comment]
Hi Shiva ,
Could you please share the checkpoint110.pth file too, as it is not available in the mentioned link.

**Comment by Shiva-sankaran** [comment]
Hi @Kalaiyarasi-Cellappan, 

Please open a new issue with more details to what checkpoint of which module do you need.

**Comment by Shiva-sankaran** [comment]
Solved by d8cb0c8a1ef08b515b566a550d62bfabfc9aa8b0

**Comment by Kalaiyarasi-Cellappan** [comment]
Hi Shiva,
    Why I can't able to download that file and couldn't retrieve it. Please check the attached image, because can't able to access the public file directory, so I need weights to download. Can you please upload the weights data.
![Uploading IMG_20230704_111247409.jpg…]()
