### ISSUE TITLE
Could you pls provide the results of ChartOCR?

### ISSUE THREAD

**Issue by xuewenyuan** [Shiva-sankaran/LineEX#2]
Thank you for your contribution. Could you pls provide the results of ChartOCR that as a argment for KP evaluation.

https://github.com/Shiva-sankaran/LineEX/blob/173343ceb92e7352427a4d937ee872b920a8d76f/modules/KP_detection/eval.py#L66

**Comment by Shiva-sankaran** [comment]
Please find the temporary download link here: https://drive.google.com/file/d/1Hhx4LH0vI1sHFerSkHNbR9lh4aq7FPAy/view?usp=share_link

**Comment by xuewenyuan** [comment]
thank you

**Comment by xuewenyuan** [comment]
@Shiva-sankaran I notice that you seem to clean the ChartOCR dataset, could you provide the clean script?
https://github.com/Shiva-sankaran/LineEX/blob/1f6f6570f164fc2a1f6d5a5d68a9ac6286502234/modules/KP_detection/eval.py#L177

**Comment by xuewenyuan** [comment]
> Please find the temporary download link here: https://drive.google.com/file/d/1Hhx4LH0vI1sHFerSkHNbR9lh4aq7FPAy/view?usp=share_link

this file is the result of figqa, could you pls the results of excelchart400k?

**Comment by Shiva-sankaran** [comment]
Hi @xuewenyuan ,

I am sorry, I don't think I will be able to provide with the requested files. Majority of the our ChartOCR implementation including the cleaning script and most of the files have been erased as we are graduating. You might still be able to replicate the results from their pipeline (https://github.com/soap117/DeepRule).

**Comment by Shiva-sankaran** [comment]
Closed, please refer to the original ChartOCR github repository to get predictions results.
