### ISSUE TITLE
Could you please provide the sample file annotation for training?

### ISSUE THREAD

**Issue by khiemng99** [Shiva-sankaran/LineEX#3]
Thank you for your contribution. Could you pls provide the file annotation for training: https://github.com/Shiva-sankaran/LineEX/blob/173343ceb92e7352427a4d937ee872b920a8d76f/modules/KP_detection/train.py#LL100C88-L100C88
Thank you so much!

**Comment by Shiva-sankaran** [comment]
Hi, @khiemng99 

Sorry for the late response was busy with my studies. We have not released the referenced file as it belongs to ChartOCR, and I could not find the file in our replica to help you out. You maybe able to find the corresponding file in the original repo (https://github.com/soap117/DeepRule).

**Comment by Shiva-sankaran** [comment]
Closed.
