### ISSUE TITLE
I used your model for map testing and found that the accuracy was high on the data you provided but very low on the other data in the paper (chart element detection module), I wonder if you can provide your data for this part?

### ISSUE THREAD

**Issue by ywking** [Shiva-sankaran/LineEX#4]

**Comment by ywking** [comment]
I used your model for map testing and found that the accuracy was high on the data you provided but very low on the other data in the paper (chart element detection module), I wonder if you can provide your data for this part?
![image](https://github.com/Shiva-sankaran/LineEX/assets/46410010/104797c2-4ba2-406a-9eab-33416f151b58)
![image](https://github.com/Shiva-sankaran/LineEX/assets/46410010/3b9188a3-1c82-43a2-9e51-9c5ba25b52bd)

**Comment by Shiva-sankaran** [comment]
Hi @ywking ,

Sorry for the delay, I was pre-occupied with my studies. I do not quite understand your question, are you trying to run our legend mapping module on the chart element detection data?

**Comment by Shiva-sankaran** [comment]
Stale.

**Comment by Shiva-sankaran** [comment]
Stale.

**Comment by sunyrain** [comment]
I think this may beacuse of the xtick legand is from 0 -100 which may not in the exact working enviroment

**Comment by sunyrain** [comment]
> I think this may beacuse of the xtick legand is from 0 -100 which may not in the exact working enviroment

I mean in the train set
