### ISSUE TITLE
weights files of modules/Grouping_legend_mapping

### ISSUE THREAD

**Issue by limaopeng1** [Shiva-sankaran/LineEX#6]
Could you please share the  weight files of modules/Grouping_legend_mapping/ckpts/mlp_ckpt.t7 and modules/Grouping_legend_mapping/ckpts/ckpt_30.t7, thanks

**Comment by Shiva-sankaran** [comment]
Hi @limaopeng1 ,

The previous link had expired it seems, the README has been updated with a temporary link containing all weights.

**Comment by Shiva-sankaran** [comment]
Resolved by https://github.com/Shiva-sankaran/LineEX/commit/2bad80769aaeb6cad9104e0c8a6d24f902c68589
