### ISSUE TITLE
Output variation with Input

### ISSUE THREAD

**Issue by shalinie22** [Shiva-sankaran/LineEX#8]
Hi @Shiva-sankaran,

I used the pretrained weights and data and got the output as same as that is given in this repository, but facing a wide variation in the generated JSON output values with the input image. 

How to check those values with the input image?

**Comment by Shiva-sankaran** [comment]
Hi @shalinie22, I am not sure what you mean by "check those values with the input image". If the generated JSON has variation when the output image is same then its most likely a scale issue
